DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
	ID INT NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(100) NOT NULL,
	HASHEDPASS VARCHAR(255) NOT NULL,
	FNAME VARCHAR (25) NOT NULL,
	LNAME VARCHAR (25) NOT NULL,
	STREET VARCHAR (100) NOT NULL,
	CITY VARCHAR (100) NOT NULL,
	USSTATE VARCHAR (100) NOT NULL,
	ZIP VARCHAR (5) NOT NULL,
	PHONE VARCHAR (11) NOT NULL,
	CARDNAME VARCHAR(100) NOT NULL,
	CARDNUMBER INT (16) NOT NULL,
	EXMONTH INT (2) NOT NULL,
	EXYEAR INT (2) NOT NULL,
	CCV INT (3) NOT NULL,
	PRIMARY KEY (ID)
);
