DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
	ID INT NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(100) NOT NULL,
	HASHEDPASS VARCHAR(255) NOT NULL,
	FNAME VARCHAR (25) NOT NULL,
	LNAME VARCHAR (25) NOT NULL,
	STREET VARCHAR (100) NOT NULL,
	CITY VARCHAR (100) NOT NULL,
	STATE VARCHAR (100) NOT NULL,
	CARD INT(16) NOT NULL,
	PRIMARY KEY (ID)
);